### ISSUE TITLE
Download TSV

### ISSUE THREAD

**Issue by d0choa** [evocellnet/kpred#2]
The download button opens the file in the browser (at least in Safari). For "not so smart" users might be confusing. I remember there was a way to force the file to be downloaded using javascript. I can check if you don't find it

**Comment by omarwagih** [comment]
This is because I'm using the new  html5 download attribute in links to force download the files instead of JS (http://www.w3schools.com/tags/att_a_download.asp). This is currently unsupported in safari and IE, which is ok for now because the file will just open in new tab. If the user wants to download the file they can save as or download all TSVs for now
